### ISSUE TITLE
compile source error (eth_components)

### ISSUE THREAD

**Issue by miroslawlis** [maxgerhardt/w5500-evb-pico-esphome#2]
Hi,
I was trying to start it but got stuck on: `esphome compile --only-generate w5500-hello.yml`, getting: "_Source is not a file system path, in expected github:..._". Was trying different strings for GitHub rep link, but none of them was working.
This is not worki either:
```
- source:
      type: git
      url: https://github.com/maxgerhardt/w5500-evb-pico-esphome.git
      ref: main
```
Any suggestions how to fix this one? 

Thx
